---
title: "WGCNA"
output:
  pdf_document: default
  html_notebook: default
---

```{r}
# Load necessary libraries
library(ggplot2)
library(ggraph)
library(gridExtra)
library(igraph)
library(WGCNA)
library(parallel)

# Read the gene expression data
data <- read.csv("../data/B73.csv", row.names = 1)
```


```{r}
set.seed(42)

# Transpose the data if genes are in columns
data <- t(data)

##log reduce the data
logDT<-log2(data)
```


```{r}
# Compute correlation matrix
set.seed(42)
logDT<-data
cor_matrix <- cor(logDT, method = "pearson")
```


```{r}
################################################################################

plotList <- list()

for (i in 1:10) {
  set.seed(42)
  threshold <- i/10
  adjacency_matrix <- abs(cor_matrix) > threshold
  
  graph <- graph_from_adjacency_matrix(adjacency_matrix, mode = "undirected", diag = FALSE)
  
  p <- ggraph(graph, layout = "fr") +
    geom_edge_link(edge_width = 0.5, edge_colour = "gray") +
    geom_node_point(size = 2, fill = "darkred", color = "black", shape = 21) +
    theme_void() +
    ggtitle(paste("Threshold:", round(threshold, 2)))
  
  plotList[[i]] <- p
}

grid.arrange(
  arrangeGrob(grobs = plotList, ncol = 2),
  ncol = 2,
  widths = c(10, 1),
  top = "Network Plots at Different Thresholds"
)

#Best threshold is 0.7
################################################################################
```


```{r}
set.seed(42)

# Set a threshold to filter weak connections
threshold <- 0.7
adjacency_matrix <- abs(cor_matrix) > threshold

# Convert to graph
graph <- graph_from_adjacency_matrix(adjacency_matrix, mode = "undirected", diag = FALSE)

# Plot the network
plot(graph, vertex.size = 5, vertex.label = NA, edge.width = 0.5)


# Save network
#write_graph(graph, file = "gene_network.graphml", format = "graphml")

#install.packages("~/Downloads/Hmisc_4.7-2.tar.gz", type="source", repos=NULL)



```

